export enum AuditAction {
  USER_CREATED = "USER_CREATED",
  USER_UPDATED = "USER_UPDATED",
  USER_DELETED = "USER_DELETED",
  USER_PASSWORD_CHANGED = "USER_PASSWORD_CHANGED",
  USER_AVATAR_DELETED = "USER_AVATAR_DELETED",
  USER_ROLE_CHANGED = "USER_ROLE_CHANGED",

  USER_BALANCE_CREATED = "USER_BALANCE_CREATED",
  USER_BALANCE_UPDATED = "USER_BALANCE_UPDATED",

  DEPOSIT_CREATED = "DEPOSIT_CREATED",
  DEPOSIT_COMPLETED = "DEPOSIT_COMPLETED",
  DEPOSIT_FAILED = "DEPOSIT_FAILED",
  DEPOSIT_CANCELLED = "DEPOSIT_CANCELLED",

  WITHDRAWAL_REQUESTED = "WITHDRAWAL_REQUESTED",
  WITHDRAWAL_APPROVED = "WITHDRAWAL_APPROVED",
  WITHDRAWAL_REJECTED = "WITHDRAWAL_REJECTED",
  WITHDRAWAL_PROCESSING = "WITHDRAWAL_PROCESSING",
  WITHDRAWAL_COMPLETED = "WITHDRAWAL_COMPLETED",
  WITHDRAWAL_FAILED = "WITHDRAWAL_FAILED",
  WITHDRAWAL_REFUNDED = "WITHDRAWAL_REFUNDED",

  TICKET_CREATED = "TICKET_CREATED",
  TICKET_MESSAGE_CREATED = "TICKET_MESSAGE_CREATED",
  TICKET_STATUS_CHANGED = "TICKET_STATUS_CHANGED",
  TICKET_PRIORITY_CHANGED = "TICKET_PRIORITY_CHANGED",
  TICKET_ASSIGNED = "TICKET_ASSIGNED",
  TICKET_UNASSIGNED = "TICKET_UNASSIGNED",
  TICKET_CATEGORY_CHANGED = "TICKET_CATEGORY_CHANGED",
  TICKET_CLOSED = "TICKET_CLOSED",
}
