import { PaymentProvider } from "../../domain/enums/payment-provider.enum";
import { PaymentType } from "../../domain/enums/payment-type.enum";

/**
 * Input required to create a payment with an external provider.
 *
 * This interface is provider-agnostic. The application layer does not
 * care whether the payment is processed by ZarinPal, Stripe, a crypto
 * provider, or another payment gateway.
 */
export interface CreatePaymentInput {
  /**
   * Amount to be paid.
   *
   * Kept as a string instead of a number to avoid floating-point
   * precision problems when dealing with monetary values.
   */
  amount: string;

  /**
   * Currency or asset being used for the payment.
   *
   * Examples:
   * - IRR
   * - USD
   * - EUR
   * - USDT
   * - BTC
   */
  currency: string;

  /**
   * Type of payment.
   *
   * Used to distinguish between fiat and cryptocurrency payments.
   */
  type: PaymentType;

  /**
   * Provider that should process the payment.
   *
   * The actual provider implementation lives in the infrastructure layer.
   */
  provider: PaymentProvider;

  /**
   * Reference to the application's own business entity.
   *
   * For example, a project could use an order ID, donation ID,
   * contribution ID, or any other business-specific identifier.
   *
   * The payment system does not need to know what this ID represents.
   */
  referenceId: string;

  /**
   * URL where the payment provider redirects the user after
   * completing or canceling the payment.
   */
  callbackUrl: string;

  /**
   * Optional description that can be displayed by the payment provider.
   */
  description?: string;

  /**
   * Optional application-specific data.
   *
   * The payment abstraction does not interpret this data.
   */
  metadata?: Record<string, string>;
}

/**
 * Result returned after successfully creating a payment.
 */
export interface CreatePaymentResult {
  /**
   * Provider that created the payment.
   */
  provider: PaymentProvider;

  /**
   * Unique payment identifier generated by the provider.
   *
   * This ID is later used when verifying the payment.
   */
  providerPaymentId: string;

  /**
   * URL where the user should be redirected to complete the payment.
   *
   * Some payment methods may not require a checkout URL.
   */
  paymentUrl?: string;
}

/**
 * Input required to verify a payment with the provider.
 */
export interface VerifyPaymentInput {
  /**
   * Payment identifier returned by the provider when the payment
   * was created.
   */
  providerPaymentId: string;

  /**
   * Original application reference associated with the payment.
   */
  referenceId: string;

  /**
   * Expected payment amount.
   *
   * The provider should verify that the actual paid amount matches
   * the expected amount.
   */
  amount: string;

  /**
   * Expected payment currency or asset.
   */
  currency: string;
}

/**
 * Result returned after verifying a payment with the provider.
 */
export interface VerifyPaymentResult {
  /**
   * Provider's payment identifier.
   */
  providerPaymentId: string;

  /**
   * Provider's transaction/reference identifier, if available.
   */
  transactionId?: string;

  /**
   * Amount confirmed by the provider.
   */
  amount: string;

  /**
   * Currency or asset confirmed by the provider.
   */
  currency: string;
}

/**
 * Application-level abstraction for payment providers.
 *
 * Implementations of this interface belong to the infrastructure layer.
 *
 * Examples:
 * - ZarinPalPaymentProvider
 * - StripePaymentProvider
 * - CryptoPaymentProvider
 *
 * The application layer depends on this abstraction instead of
 * depending directly on any payment provider or SDK.
 */
export interface PaymentProviderInterface {
  /**
   * Creates a payment with the selected external provider.
   */
  createPayment(input: CreatePaymentInput): Promise<CreatePaymentResult>;

  /**
   * Verifies the payment with the external provider.
   *
   * A callback from a payment provider should not be trusted by itself;
   * the provider should be queried to confirm the actual payment.
   */
  verifyPayment(input: VerifyPaymentInput): Promise<VerifyPaymentResult>;
}
